-- S1 — plot geometry + the quetzal reserve, as the map spine.
--
-- DESIGN: NO PostGIS. The PGlite test substrate (and a $0/no-Docker box) has no
-- PostGIS extension, so geometry is stored as GeoJSON in plain `jsonb` columns —
-- not the `geometry` type. Area/centroid are computed in TypeScript with turf
-- (src/lib/geo/placeholder.ts), unit-tested, and their OUTPUT is embedded below as
-- literal GeoJSON. This keeps the whole slice replayable in PGlite. PostGIS stays
-- a documented LATER upgrade (swap jsonb -> geometry(Polygon,4326), backfill).
--
-- Grant posture (AD-8): grant_hygiene locked `alter default privileges`, so the
-- new reserve_zones table gets NO grant by default — we must `grant select` to
-- authenticated explicitly, and RLS gates it authenticated-only (anon reads
-- nothing), matching 20260620140000_auth_required_rls.

begin;

-- ──────────────────────────────────────────────────────────────────────────
-- plots: geometry (GeoJSON jsonb) + DEM-derived scalars (left null for now)
-- ──────────────────────────────────────────────────────────────────────────
alter table plots
  add column if not exists geom             jsonb,   -- GeoJSON Polygon (nullable)
  add column if not exists centroid         jsonb,   -- GeoJSON Point   (nullable)
  add column if not exists elevation_min_m  numeric, -- DEM-derived, filled offline later
  add column if not exists elevation_mean_m numeric,
  add column if not exists elevation_max_m  numeric,
  add column if not exists slope_deg_mean   numeric,
  add column if not exists aspect_deg_mean  numeric;

-- ──────────────────────────────────────────────────────────────────────────
-- reserve_zones: the protected quetzal reserve as a first-class geometry layer.
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists reserve_zones (
  id      text    primary key,
  name    text    not null,
  kind    text    not null,          -- e.g. 'reserve', 'riparian', 'shade-corridor'
  geom    jsonb   not null,          -- GeoJSON Polygon
  area_ha numeric,
  notes   text
);

-- RLS — authenticated-only read, mirroring the "authenticated read" idiom used
-- for every other table in 20260620140000_auth_required_rls.
alter table reserve_zones enable row level security;
drop policy if exists "authenticated read" on reserve_zones;
create policy "authenticated read" on reserve_zones
  for select to authenticated using (true);

-- AD-8: default privileges are locked, so grant SELECT explicitly (else the table
-- silently returns zero rows to every caller). No write grants — the app is read-only.
grant select on reserve_zones to authenticated;

-- ──────────────────────────────────────────────────────────────────────────
-- SEED — *** PLACEHOLDER GEOMETRY *** (idempotent).
--
-- !!! HUMAN/FAMILY GATE !!!
-- These polygons are APPROXIMATE squares sized by each plot's area_ha and scattered
-- on a grid around Volcán (~8.78°N, 82.63°W). They are NOT the real traced farm
-- boundaries — they exist only so the map renders end-to-end. Replace with the
-- family's surveyed/traced boundaries (and the real reserve outline) when available;
-- at that point also backfill the DEM scalars and consider the PostGIS upgrade.
-- Generated by scripts/_gen-geom.ts from src/lib/geo/placeholder.ts.
-- ──────────────────────────────────────────────────────────────────────────

update plots set geom = '{"type":"Polygon","coordinates":[[[-82.641276,8.776908],[-82.639413,8.776908],[-82.639413,8.778761],[-82.641276,8.778761],[-82.641276,8.776908]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.640344,8.777835]}'::jsonb where id = 'p-tizingal-alto';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.634782,8.777039],[-82.633181,8.777039],[-82.633181,8.778631],[-82.634782,8.778631],[-82.634782,8.777039]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.633982,8.777835]}'::jsonb where id = 'p-baru-vista';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.628777,8.776682],[-82.62646,8.776682],[-82.62646,8.778988],[-82.628777,8.778988],[-82.628777,8.776682]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.627618,8.777835]}'::jsonb where id = 'p-talamanca';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.62235,8.776746],[-82.620161,8.776746],[-82.620161,8.778924],[-82.62235,8.778924],[-82.62235,8.776746]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.621255,8.777835]}'::jsonb where id = 'p-nueva-suiza';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.641218,8.783296],[-82.63947,8.783296],[-82.63947,8.785035],[-82.641218,8.785035],[-82.641218,8.783296]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.640344,8.784166]}'::jsonb where id = 'p-paso-ancho';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.634987,8.783164],[-82.632975,8.783164],[-82.632975,8.785166],[-82.634987,8.785166],[-82.634987,8.783164]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.633981,8.784165]}'::jsonb where id = 'p-bambito';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.628351,8.783436],[-82.626886,8.783436],[-82.626886,8.784894],[-82.628351,8.784894],[-82.628351,8.783436]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.627618,8.784165]}'::jsonb where id = 'p-las-lagunas';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.622292,8.783134],[-82.620219,8.783134],[-82.620219,8.785196],[-82.622292,8.785196],[-82.622292,8.783134]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.621256,8.784165]}'::jsonb where id = 'p-palmira';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.641297,8.789547],[-82.639391,8.789547],[-82.639391,8.791444],[-82.641297,8.791444],[-82.641297,8.789547]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.640344,8.790496]}'::jsonb where id = 'p-cuesta-piedra';
update plots set geom = '{"type":"Polygon","coordinates":[[[-82.634807,8.789674],[-82.633156,8.789674],[-82.633156,8.791317],[-82.634807,8.791317],[-82.634807,8.789674]]]}'::jsonb, centroid = '{"type":"Point","coordinates":[-82.633982,8.790495]}'::jsonb where id = 'p-rio-sereno';

-- The ~200-ha quetzal reserve (BRAND.reserveHectares). Idempotent upsert.
insert into reserve_zones (id, name, kind, geom, area_ha, notes)
values (
  'rz-quetzal',
  'Quetzal Cloud-Forest Reserve',
  'reserve',
  '{"type":"Polygon","coordinates":[[[-82.682228,8.829605],[-82.669372,8.829605],[-82.669372,8.842395],[-82.682228,8.842395],[-82.682228,8.829605]]]}'::jsonb,
  200.9,
  'PLACEHOLDER outline pending the real traced reserve boundary (human/family gate).'
)
on conflict (id) do update
  set name = excluded.name,
      kind = excluded.kind,
      geom = excluded.geom,
      area_ha = excluded.area_ha,
      notes = excluded.notes;

commit;
